name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Get the version
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build
        run: |
          dotnet pack src/KeysConfiguration --output .publish/X /p:Version=${{ steps.get-version.outputs.VERSION }}

      - name: Push
        run: |
          dotnet nuget push .publish/X/wk.KeysConfiguration.${{ steps.get-version.outputs.VERSION }}.nupkg \
            -s https://api.nuget.org/v3/index.json \
            -k ${{ secrets.NUGET_TOKEN }}
